services:
  db:
    image: postgres:16
    container_name: postgresRosDb
    environment:
      POSTGRES_USER: ros1234
      POSTGRES_PASSWORD: ros1234$
      POSTGRES_DB: rosdb
    ports:
      - "5432:5432"

